/////////////////////////////////
//   DEV DUMMY PARTICIAPNTS    //
/////////////////////////////////
export const INITIAL_PARTICIPANTS_DUMMY = [
  {
    api_url: "/participants/5e9e053f-91de-4df1-9749-9743230b6174",
    call_direction: "in",
    displayName: "api_user",
    encryption: "On",
    has_media: false,
    isMuted: false,
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "NO",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "api_user",
    presentation_supported: "NO",
    fecc_supported: "NO",
    protocol: "api",
    role: "guest",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlightOrder: 1,
    start_time: 1717463486.0425053,
    uri: "api_user",
    external_node_uuid: "",
    uuid: "5e9e053f-91de-4df1-9749-9743230b6174",
    vendor:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 PexRTC",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    isCameraMuted: false,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
  {
    api_url: "/participants/9fa2b838-c4e9-4c5a-813a-0ee7b44b1441",
    call_direction: "in",
    displayName: "Richard Felix",
    encryption: "On",
    has_media: true,
    isMuted: false,
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "YES",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "Richard Felix",
    presentation_supported: "YES",
    fecc_supported: "NO",
    protocol: "webrtc",
    role: "chair",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlightOrder: 0,
    start_time: 1717463529.9298756,
    uri: "Richard Felix",
    external_node_uuid: "",
    uuid: "9fa2b838-c4e9-4c5a-813a-0ee7b44b1441",
    vendor:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Webapp3/6.0.0+bc6f3c1cf",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    isCameraMuted: false,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },

  {
    api_url: "/participants/f4eb23e4-6403-4ad4-a61c-7844c489e638",
    call_direction: "out",
    displayName: "sip:presenter2@prodfs.webcasts.com",
    encryption: "On",
    has_media: true,
    isMuted: false,
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "YES",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "presenter2@prodfs.webcasts.com",
    presentation_supported: "NO",
    fecc_supported: "NO",
    protocol: "sip",
    role: "guest",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlightOrder: 0,
    start_time: 1717038799.2610059,
    uri: "sip:presenter2@prodfs.webcasts.com",
    external_node_uuid: "",
    uuid: "f4eb23e4-6403-4ad4-a61c-7844c489e638",
    vendor: "FreeSWITCH-mod_sofia/1.10.11-release-25-f24064f7c9~64bit",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    isCameraMuted: false,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
  {
    api_url: "/participants/34981533-01ed-45a3-a586-4f86e8d59310",
    call_direction: "out",
    displayName: "rtmp: stream",
    encryption: "On",
    has_media: true,
    isMuted: false,
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "YES",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "presenter3@prodfs.webcasts.com",
    presentation_supported: "NO",
    fecc_supported: "NO",
    protocol: "rtmp",
    role: "guest",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlightOrder: 0,
    start_time: 1717038807.233808,
    uri: "sip:presenter3@prodfs.webcasts.com",
    external_node_uuid: "",
    uuid: "34981533-01ed-45a3-a586-4f86e8d59310",
    vendor: "FreeSWITCH-mod_sofia/1.10.11-release-25-f24064f7c9~64bit",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    isCameraMuted: false,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
  {
    api_url: "/participants/4addf56c-2dbe-4303-8912-7b1355a7c322",
    call_direction: "out",
    displayName: "sip:presenter4@prodfs.webcasts.com",
    encryption: "On",
    has_media: true,
    isMuted: false,
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "YES",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "presenter4@prodfs.webcasts.com",
    presentation_supported: "NO",
    fecc_supported: "NO",
    protocol: "sip",
    role: "chair",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlightOrder: 1,
    start_time: 1717038815.5377162,
    uri: "sip:presenter4@prodfs.webcasts.com",
    external_node_uuid: "",
    uuid: "4addf56c-2dbe-4303-8912-7b1355a7c322",
    vendor: "FreeSWITCH-mod_sofia/1.10.11-release-25-f24064f7c9~64bit",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    isCameraMuted: true,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
  {
    api_url: "/participants/48f0321b-4010-4a9e-9d14-50f23627929e",
    call_direction: "out",
    displayName: "sip:presenter5@prodfs.webcasts.com",
    encryption: "On",
    has_media: true,
    isMuted: false,
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "YES",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "presenter5@prodfs.webcasts.com",
    presentation_supported: "NO",
    fecc_supported: "NO",
    protocol: "sip",
    role: "chair",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlightOrder: 0,
    start_time: 1717038822.6079524,
    uri: "sip:presenter5@prodfs.webcasts.com",
    external_node_uuid: "",
    uuid: "48f0321b-4010-4a9e-9d14-50f23627929e",
    vendor: "FreeSWITCH-mod_sofia/1.10.11-release-25-f24064f7c9~64bit",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    isCameraMuted: false,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
  {
    api_url: "/participants/923f3865-a8cd-40e3-959e-d5e19cdebd0a",
    call_direction: "in",
    display_name: "John Woo",
    encryption: "On",
    has_media: true,
    is_muted: "YES",
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "YES",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "Richard Felix",
    presentation_supported: "YES",
    fecc_supported: "NO",
    protocol: "webrtc",
    role: "chair",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlight: 3,
    start_time: 1718938269.2712307,
    uri: "Richard Felix",
    external_node_uuid: "",
    uuid: "923f3865-a8cd-40e3-959e-d5e19cdebd0a",
    vendor:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Webapp3/6.0.0+861f7a908",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    is_video_muted: true,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
];

/////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
const me = {
  callType: "video",
  canControl: true,
  canChangeLayout: true,
  canDisconnect: true,
  canFecc: false,
  canMute: true,
  canRaiseHand: true,
  canSpotlight: true,
  canTransfer: true,
  displayName: "Richard Felix",
  overlayText: "Richard Felix",
  handRaisedTime: 0,
  identity: "648afde9-a999-492b-9d8d-5322763422ea",
  isCameraMuted: false,
  isConjoined: false,
  isConnecting: false,
  isEndpoint: false,
  isExternal: false,
  isIdpAuthenticated: false,
  isGateway: false,
  isHost: true,
  isMainVideoDroppedOut: false,
  isMuted: true,
  isPresenting: false,
  isSpotlight: false,
  isStreaming: false,
  isVideoSilent: false,
  isWaiting: false,
  needsPresentationInMix: false,
  protocol: "webrtc",
  raisedHand: false,
  role: "chair",
  rxPresentation: true,
  serviceType: "conference",
  spotlightOrder: 0,
  startAt: "2024-07-01T02:33:07.098Z",
  startTime: 1719801187.0984137,
  uri: "Richard Felix",
  uuid: "648afde9-a999-492b-9d8d-5322763422ea",
  vendor:
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Webapp3/6.0.0+861f7a908",
  rawData: {
    api_url: "/participants/648afde9-a999-492b-9d8d-5322763422ea",
    call_direction: "in",
    display_name: "Richard Felix",
    encryption: "On",
    has_media: true,
    is_muted: "YES",
    is_presenting: "NO",
    is_streaming_conference: false,
    is_video_call: "YES",
    is_audio_only_call: "NO",
    local_alias: "52569",
    overlay_text: "Richard Felix",
    presentation_supported: "YES",
    fecc_supported: "NO",
    protocol: "webrtc",
    role: "chair",
    rx_presentation_policy: "ALLOW",
    service_type: "conference",
    spotlight: 0,
    start_time: 1719801187.0984137,
    uri: "Richard Felix",
    external_node_uuid: "",
    uuid: "648afde9-a999-492b-9d8d-5322763422ea",
    vendor:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Webapp3/6.0.0+861f7a908",
    is_external: false,
    is_conjoined: false,
    transfer_supported: "YES",
    disconnect_supported: "YES",
    mute_supported: "YES",
    buzz_time: 0,
    call_tag: "",
    is_video_muted: false,
    is_video_silent: false,
    is_main_video_dropped_out: false,
    needs_presentation_in_mix: false,
    show_live_captions: false,
    is_idp_authenticated: false,
    send_to_audio_mixes: [
      {
        mix_name: "main",
        prominent: false,
      },
    ],
    receive_from_audio_mix: "main",
    layout_group: null,
  },
};
